# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    branches: [ main, master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run tests before deployment
        run: |
          pytest
          
      - name: Build Docker image
        run: |
          docker build -t jira-github-health-agent:${{ github.sha }} .
          docker tag jira-github-health-agent:${{ github.sha }} jira-github-health-agent:latest
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
          
      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: jira-github-health-agent
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag jira-github-health-agent:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag jira-github-health-agent:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster jira-github-agent-cluster --service jira-github-agent-service --force-new-deployment
          
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      - name: Test with pytest
        run: |
          pytest --cov=./